spring.application.name=ferreteria-guillermo-api

spring.datasource.url=jdbc:postgresql://localhost:5432/ferreteria_guillermo
spring.datasource.username=postgres
spring.datasource.password=swmyri

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Correo que recibirá las solicitudes
app.mail.to=${MAIL_TO}